services:
  db:
    image: postgres:17.0
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
    - pgdata:/var/lib/postressql/data

volumes:
    pgdata:
